# These are supported funding model platforms

github: moscaverd

# Other options (uncomment and configure as needed):
# ko_fi: your_kofi_username
# patreon: your_patreon_username
# open_collective: your_open_collective
# custom: ["https://www.paypal.me/yourpaypal", "https://buy.me/a/coffee"]
